# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require_relative '../xt/preamble.rb'
require_relative '../xt/hardware.rb'
require_relative '../xt/cachier_monkeypatch.rb'
require_relative '../xt/browser.rb'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV['VAGRANT_LOG'] = 'debug'
VAGRANTFILE_API_VERSION = "2"


CONFIG = File.join(File.dirname(__FILE__), "config.rb")

# Defaults for config options defined in CONFIG
# FIX https://github.com/coreos/coreos-vagrant/issues/98
$enable_serial_logging = false

if File.exist?(CONFIG)
  require CONFIG
end

######################################################
#                                                    #
#                   VM-CHEF-SERVER                   #
#                   **************                   #
#                                                    #
######################################################
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Checks prequisites and plugins
  pre = Preamble.new(config, ">= 1.7.1")
  
  ######### CACHIER
  config.cache.scope = :box
  
  ######### OMNIBUS
  config.omnibus.chef_version = "12.0.0" # :latest
  
  ######### VBGUEST
  #config.vbguest.auto_update = false
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  # Whether to check the correct additions version only.
  config.vbguest.no_install = true
  
  ######### BUTCHER
  config.butcher.enabled = true # Default
  config.butcher.verify_ssl = false
  #config.butcher.client_key = "local-workstation.pem"
  #config.butcher.client_name = "root"
  
  # Calculate Resources
  hard = Hardware.new(8, 6144) # CPUs, RAM
  using_cpus = hard.processing_units
  using_memory = hard.memory_mb / 4 # 1/4 RAM
  puts "Found #{hard.processing_units} Cores. Using #{using_cpus} Cores"
  puts "Found #{hard.memory_mb} MB Memory. Using #{using_memory} MB Memory"
  
  
  {
    [:up] => "https://192.168.1.2:9191/",
    [:provision] => "https://192.168.1.2:9191/",
    [:resume] => "https://192.168.1.2:9191/",
    #[:suspend] => "",
    #[:halt] => "",
    #[:destroy] => ""
  }.each do |command, trigger|
    config.trigger.after command, :stdout => true, :force => true do
      Browser.new().open(trigger)
    end
  end
  
  config.vm.network :private_network, ip: "192.168.1.2"
  # Chef-Server-Ports
  config.vm.network :forwarded_port, guest: 9191, host: 9191
  
  config.vm.synced_folder "../data/global", "/globaldata"
  config.vm.synced_folder "../data/chef-server/", "/data/chef-server"
  config.vm.synced_folder "../data/chef-client/", "/data/chef-client"
  config.vm.synced_folder "../data/chef-server/log/", "/var/log/chef-server"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-chef-server"
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    vb.customize ["modifyvm", :id, "--cpus", using_cpus]
    vb.customize ["modifyvm", :id, "--memory", using_memory]
    vb.gui = false
    
    # Fix tsc unstable -> "kernel: Clocksource tsc unstable (delta = 302978408 ns).  Enable clocksource failover by adding clocksource_failover kernel parameter."
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--enable-timesync"]
    # Fix symlinks -> Vagrant-713: https://github.com/mitchellh/vagrant/issues/713
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/tmp_vagrant-cache_chef", "1"]
  end
  
  config.vm.define "vm-chef-server" do |host|
    host.vm.hostname = "vm-chef-server"
    host.vm.box = "wlc/centos-6.6"
    
    CHEF_JSON = JSON.parse(Pathname(__FILE__).dirname.join('.', 'chef.json').read)
    
    host.vm.provision "chef_solo" do |chef|
      chef.custom_config_path = "vagrant_chef_config"
      chef.cookbooks_path = "../vm-chef-workstation/wlc-chef-repo/cookbooks"
      chef.roles_path = "../vm-chef-workstation/wlc-chef-repo/roles"
      chef.data_bags_path = "../vm-chef-workstation/wlc-chef-repo/data_bags"
      
      CHEF_JSON['run_list'].each do |recipe|
        puts recipe
        chef.add_recipe(recipe)
      end if CHEF_JSON['run_list']
      
      # Recipe is broken since it uses deprecated download URLs
      # see https://github.com/opscode/opscode-omnitruck#deprecated-urls
      #"package_file" => "https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.3-1_amd64.deb"
      #"package_file" => "https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-server-11.1.6-1.el6.x86_64.rpm"
      chef.run_list = CHEF_JSON.delete('run_list')
      chef.json = CHEF_JSON
    end
    host.vm.provision "shell", path: "../data/chef-server/script/copy_validator"
  end
end
