FROM yserz/docker-vagrant-centos-7-minivm

MAINTAINER Michael Koppen <michael.koppen@googlemail.com>

RUN curl -L https://www.opscode.com/chef/install.sh | bash -s -- -v 12.0.1

CMD ["/usr/sbin/init"]