# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require_relative '../xt/preamble.rb'
require_relative '../xt/hardware.rb'
require_relative '../xt/browser.rb'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV['VAGRANT_LOG'] = 'debug'
VAGRANTFILE_API_VERSION = "2"


CONFIG = File.join(File.dirname(__FILE__), "config.rb")

# Defaults for config options defined in CONFIG
# FIX https://github.com/coreos/coreos-vagrant/issues/98
$enable_serial_logging = false

if File.exist?(CONFIG)
  require CONFIG
end

######################################################
#                                                    #
#                     VM-WLC-TEST                    #
#                     ***********                    #
#                                                    #
######################################################
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Checks prequisites and plugins
  pre = Preamble.new(config, ">= 1.7.1")
  
  ######### CACHIER
  # Configure cached packages to be shared between instances of the same base box.
  # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
  config.cache.scope = :box
  
  ######### OMNIBUS
  # config.omnibus.install_url = 'http://acme.com/install.sh'
  config.omnibus.chef_version = "12.0.0" # :latest
  
  ######### VBGUEST
  #config.vbguest.auto_update = false
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  # Whether to check the correct additions version only.
  config.vbguest.no_install = true
  
  ######### BUTCHER
  config.butcher.enabled = true # Default
  config.butcher.verify_ssl = false
  #config.butcher.client_key = "local-workstation.pem"
  #config.butcher.client_name = "root"
  
  
  # Calculate Resources
  hard = Hardware.new(8, 6144) # CPUs, RAM
  using_cpus = hard.processing_units
  using_memory = hard.memory_mb / 4 # 1/2 RAM
  puts "Found #{hard.processing_units} Cores. Using #{using_cpus} Cores"
  puts "Found #{hard.memory_mb} MB Memory. Using #{using_memory} MB Memory"
  
  
  {
    #[:up] => "",
    #[:provision] => "",
    #[:resume] => "",
    #[:suspend] => "",
    #[:halt] => "",
    #[:destroy] => ""
  }.each do |command, trigger|
    config.trigger.after command, :stdout => true, :force => true do
      Browser.new().open(trigger)
    end
  end
  
  config.vm.network :private_network, ip: "192.168.4.2"
  
  config.vm.synced_folder "../data/global/", "/globaldata"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-wlc-test"
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
    vb.customize ["modifyvm", :id, "--cpus", using_cpus]
    vb.customize ["modifyvm", :id, "--memory", using_memory]
    vb.gui = false
    # Fix tsc unstable -> "kernel: Clocksource tsc unstable (delta = 302978408 ns).  Enable clocksource failover by adding clocksource_failover kernel parameter."
    vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--enable-timesync"]
    # Fix symlinks -> Vagrant-713: https://github.com/mitchellh/vagrant/issues/713
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//data", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//tmp/vagrant-cache", "1"]
  end
  
  
  # Definition of the Proxy-Instance running docker containers
  config.vm.define "vm-wlc-test" do |host|
    host.vm.hostname = "vm-wlc-test"
    #host.vm.post_up_message = 'Welcome to the We Love Coding: VM-DEV-HOST!'
    host.vm.box = "wlc/centos-7.0"
    #host.ssh.username = "vagrant"
    
    host.vm.provision "docker"
    host.vm.provision "shell", path: "../data/global/script/docker/docker_load_images"
    host.vm.provision "docker" do |d|
      d.build_image "/globaldata/container/minivm_sysd", args: "-t yserz/docker-vagrant-centos-7-minivm"
      d.version = :latest # Default is :latest
    end
    host.vm.provision "docker" do |d|
      d.build_image "/globaldata/container/minivm_sysd_chef", args: "-t yserz/docker-vagrant-centos-7-minivm_chef"
      d.version = :latest # Default is :latest
    end
    host.vm.provision "shell", path: "../data/global/script/docker/docker_save_images"
    
    
    if Vagrant.has_plugin?('vagrant-triggers')
      # config.trigger.before :destroy, :stdout => true, :force => true do
      #   info "Updating Docker cache..."
      #   run_remote "sudo chmod 755 /vagrant/docker_save_images && /vagrant/docker_save_images"
      # end
    end
    
    
    
    CHEF_JSON = JSON.parse(Pathname(__FILE__).dirname.join('.', 'chef.json').read)
    
    host.vm.provision "chef_client" do |chef|
      # Solves the Chef SSL warning
      # http://stackoverflow.com/questions/22991561/chef-solo-ssl-warning-when-provisioning
      # Note: This function needs a SSL-Certificate installed in Chef-Server
      #chef.custom_config_path = "vagrant_chef_config"
      
      #chef.encrypted_data_bag_secret_key_path = "../data_bag_key.pem"
      chef.chef_server_url = "https://192.168.1.2:9191/"
      chef.validation_key_path = "../data/chef-client/credentials/chef-validator.pem"
      #chef.client_key_path = "/vagrant/local-workstation.pem"
      
      CHEF_JSON['run_list'].each do |recipe|
        puts recipe
        chef.add_recipe(recipe)
      end if CHEF_JSON['run_list']
      
      chef.run_list = CHEF_JSON.delete('run_list')
      chef.json = CHEF_JSON
    end
  end
end
