# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../../xt/preamble.rb'
require_relative '../../xt/butcher_monkeypatch.rb'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
ENV['VAGRANT_LOG'] = 'info'
ENV['CHEF_LOG'] = 'info'
VAGRANTFILE_API_VERSION = "2"

######################################################
#                                                    #
#             CONTAINER-WORKSTATION-LOCAL            #
#             ***************************            #
#                                                    #
######################################################
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Checks prequisites and plugins
  pre = Preamble.new(config, ">= 1.7.1")
  
  ######### CACHIER
  # Configure cached packages to be shared between instances of the same base box.
  # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
  config.cache.scope = :box
  
  ######### OMNIBUS
  # config.omnibus.install_url = 'http://acme.com/install.sh'
  config.omnibus.chef_version = "12.0.1" # :latest
  
  ######### VBGUEST
  #config.vbguest.auto_update = false
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  # Whether to check the correct additions version only.
  config.vbguest.no_install = true
  
  ######### BUTCHER
  config.butcher.enabled = true # Default
  config.butcher.verify_ssl = false
  #config.butcher.client_key = "local-workstation.pem"
  #config.butcher.client_name = "root"
  
  
  config.vm.define 'container-local-workstation' do |ws|
    
    # Chef-Workstation
    ws.vm.hostname = 'container-local-workstation'
    jk.vm.network :forwarded_port, guest: 22, host: 22001, id: "ssh", auto_correct: true
    
    ws.vm.provider "docker" do |d|
      d.volumes = [
        "/data/chef-client:/data", 
        "/vagrant/chef-repo:/home/vagrant/chef-repo"
      ]
      d.image = "yserz/docker-vagrant-centos-7-minivm_runit"
      d.vagrant_machine = "vm-chef-server"
      d.vagrant_vagrantfile = "../Vagrantfile"
      d.force_host_vm = true
      d.has_ssh = true
    end
    
    CHEF_JSON = JSON.parse(Pathname(__FILE__).dirname.join('.', 'chef.json').read)
    
    ws.vm.provision "chef_client" do |chef|
      # Solves the Chef SSL warning
      # http://stackoverflow.com/questions/22991561/chef-solo-ssl-warning-when-provisioning
      # Note: This function needs a SSL-Certificate installed in Chef-Server
      #chef.custom_config_path = "vagrant_chef_config"
      
      #chef.encrypted_data_bag_secret_key_path = "../data_bag_key.pem"
      chef.chef_server_url = "https://192.168.1.2:9191/"
      chef.validation_key_path = "../../data/chef-client/credentials/chef-validator.pem"
      #chef.client_key_path = "/vagrant/local-workstation.pem"
      
      CHEF_JSON['run_list'].each do |recipe|
        puts recipe
        chef.add_recipe(recipe)
      end if CHEF_JSON['run_list']
      
      chef.run_list = CHEF_JSON.delete('run_list')
      chef.json = CHEF_JSON
    end
    
    ws.vm.provision "shell" do |s|
     p = File.expand_path("../../../", __FILE__)
     s.path = p + "/data/chef-client/script/init_knife"
    end
  end
end
