# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative '../../xt/preamble.rb'
require_relative '../../xt/butcher_monkeypatch.rb'
require_relative '../../xt/browser.rb'

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
ENV['VAGRANT_LOG'] = 'info'
ENV['CHEF_LOG'] = 'info'
VAGRANTFILE_API_VERSION = "2"

######################################################
#                                                    #
#                 CONTAINER-JENKINS                  #
#                 *****************                  #
#                                                    #
######################################################
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Checks prequisites and plugins
  pre = Preamble.new(config, ">= 1.6.5")
  
  ######### CACHIER
  # Configure cached packages to be shared between instances of the same base box.
  # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
  # Disable cache because of failing JDK installation
  config.cache.auto_detect = false
  config.cache.enable :yum
  config.cache.enable :chef
  
  ######### OMNIBUS
  # config.omnibus.install_url = 'http://acme.com/install.sh'
  config.omnibus.chef_version = "12.0.0" # "11.16.4" # :latest
  
  ######### VBGUEST
  #config.vbguest.auto_update = false
  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = true
  # Whether to check the correct additions version only.
  config.vbguest.no_install = true
  
  ######### BUTCHER
  config.butcher.enabled = true # Default
  config.butcher.verify_ssl = false
  #config.butcher.client_key = "local-workstation.pem"
  #config.butcher.client_name = "root"
  
  
  {
    [:up] => "http://192.168.2.2:8080/",
    [:provision] => "http://192.168.2.2:8080/",
    [:resume] => "http://192.168.2.2:8080/",
    #[:suspend] => "",
    #[:halt] => "",
    #[:destroy] => ""
  }.each do |command, trigger|
    config.trigger.after command, :stdout => true, :force => true do
      Browser.new().open(trigger)
    end
  end

  config.vm.define 'container-jenkins' do |jk|
    
    # Chef-Workstation
    jk.vm.hostname = 'container-jenkins'
    jk.vm.network "private_network", ip: "192.168.2.5"
    jk.vm.network :forwarded_port,
      guest: 22,
      host: 2202
    #ws.ssh.username = "vagrant"
    #v.ssh.private_key_path = "../key.pem"
    jk.ssh.host = "localhost"
    jk.ssh.port = 2202
    
    jk.vm.provider "docker" do |d|
      d.privileged = true
      d.volumes = [
        "/globaldata/:/globaldata",
        "/data/jenkins/:/data",
        "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ]
      d.ports = ["8080:8080"]
      d.image = "yserz/docker-vagrant-centos-7-minivm_chef"
      d.expose = [22, 8080]
      d.vagrant_machine = "vm-development"
      d.vagrant_vagrantfile = "../Vagrantfile"
      d.force_host_vm = true
      d.has_ssh = true
    end
    
    jk.vm.provision "shell", inline: "sudo groupadd --force --gid 1000 --system jenkins && useradd --uid 1000 --gid 1000 --home /var/lib/jenkins --shell /bin/false jenkins"
    jk.vm.provision "shell", path: "../../data/global/script/cron/configure_cron"
    
    CHEF_JSON = JSON.parse(Pathname(__FILE__).dirname.join('.', 'chef.json').read)
    
    jk.vm.provision "chef_client" do |chef|
      # Solves the Chef SSL warning
      # http://stackoverflow.com/questions/22991561/chef-solo-ssl-warning-when-provisioning
      # Note: This function needs a SSL-Certificate installed in Chef-Server
      #chef.custom_config_path = "vagrant_chef_config"
      
      #chef.encrypted_data_bag_secret_key_path = "../data_bag_key.pem"
      chef.chef_server_url = "https://192.168.1.2:9191/"
      chef.validation_key_path = "../../data/chef-client/credentials/chef-validator.pem"
      #chef.client_key_path = "/vagrant/local-workstation.pem"
      #chef.log_level = :info
      
      CHEF_JSON['run_list'].each do |recipe|
        puts recipe
        chef.add_recipe(recipe)
      end if CHEF_JSON['run_list']
      
      chef.run_list = CHEF_JSON.delete('run_list')
      chef.json = CHEF_JSON
    end
  end
end
